version: "2"
services:
  postgres:
    image: postgres
    container_name: postgres-todo-task
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5431:5432
    volumes:
      - ${PWD}/db_data:/var/lib/postgresql/data
